          export enable_ccache=on

        fi

        curl -L https://github.com/blueloveTH/aseprite/releases/download/v0.01/skia.zip --output skia.zip

        7z x skia.zip

        cmake -S . -B build -G Ninja \

          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \

          -DENABLE_UI=${{ matrix.enable_ui }} \

          -DENABLE_CCACHE=$enable_ccache \

          -DLAF_BACKEND=skia \

          -DSKIA_DIR=./skia \

          -DSKIA_LIBRARY_DIR=./skia/out/Release-x64 \

          -DSKIA_LIBRARY=./skia/out/Release-x64/skia.lib

    - name: Compiling

      shell: bash

      run: |

        cd build && ninja

    - uses: actions/upload-artifact@v3

      with:

        name: aseprite

        path: |

          D:/a/aseprite/aseprite/build/bin/data

          D:/a/aseprite/aseprite/build/bin/aseprite.exe
